### ISSUE TITLE
Ability to manage recaptcha's config

### ISSUE THREAD

**Issue by dr-dimitru** [appshore/Meteor-reCAPTCHA#1]
Any of this [config options](https://developers.google.com/recaptcha/docs/display#config) is available in this package? If yes, - how to set them?

**Comment by dr-dimitru** [comment]
Hi @appshore any update around this one?
Currently need `hl` option to set locale.
Most of other options is also indeed needed.

**Comment by dr-dimitru** [comment]
I believe this is fixed in #2 , right?

**Comment by ecsmyth** [comment]
Hi @dr-dimitru, this should be fixed in the latest version. I'm releasing on Atmosphere in a few minutes.

**Comment by dr-dimitru** [comment]
I see no updates
![screen shot 2016-03-09 at 12 27 55 am](https://cloud.githubusercontent.com/assets/1686778/13617061/dd3b051e-e58d-11e5-80bf-2ea397f5f6d5.png)
![screen shot 2016-03-09 at 12 27 22 am](https://cloud.githubusercontent.com/assets/1686778/13617062/dd65b750-e58d-11e5-8e71-faaf80890106.png)

**Comment by ecsmyth** [comment]
It will be a little while longer. I'm waiting on maintainer permissions to the existing package. I want to keep it as "appshore:recaptcha" rather than republishing as "ecsmyth:recaptcha"

**Comment by dr-dimitru** [comment]
@ecsmyth agree, it would be perfect to keep same package name, as there is already three of them.
Thank you, waiting for update. Cheers.

**Comment by dr-dimitru** [comment]
ping. should we close this one?

**Comment by ecsmyth** [comment]
Fixed in version 2.1.0
Pushed to Atmosphere on March 9, 2016
